### ISSUE TITLE
Session lost in a controller creating a new Payment

### ISSUE THREAD

**Issue by Noohmsul** [alcalyn/payplug-bundle#14]
Hi,

So I have this simple yet very strange problem using this bundle : in my shop I use sessions to store the customer's cart, but when I try to generate a payment, the cart is suddenly lost.

To be more precise : I have a controler called payplugAction, in which I try to generate my payment. In this controler, when this line is writtent : 
`
$payment = new Payment();
`
The session becomes empty. 
When the line isn't here, the session works fine and contains the customer's cart.
Note that the problem happens **before** the execution of this line ! This is the simple presence of this line in my code that generates the problem.
I know this by putting : 
`$session = $request->getSession();
 var_dump($session);`
before the line...
Also note that the session isn't really erased, because when I comment the line, the cart content is in the session again.

Any idea?
Thanks

**Comment by alcalyn** [comment]
I don't think that it is related to this bundle because it don't use session to store anything.
But it could be something like a side effect, I may help you if you provide you controller code which create the payment url.

Another note: I don't have used this bundle since a long time, I don't know if it still works when Payplug API has changed a little. I only know that it is continuously downloaded so I think some people still use it at this time.

**Comment by Noohmsul** [comment]
Ok my bad, I just discovered that the problem were not related to your bundle. I managed to implement the payplug library, and had the exact same problem when trying to generate a payment...

I didn't have the time to investigate more about this, so I resolved my issue by generating payments and urls without the library (so without external classes - all is in the controller), and now it strangely works...

**Comment by alcalyn** [comment]
Ok, I cant do more if you don't provide php debug stack trace or source code, but if you consider the issue is resolved, feel free to close it :D

**Comment by Noohmsul** [comment]
I'll not bother you if your bundle is not the problem :) And it seems to work with my method ...
