### ISSUE TITLE
Got error on simulating IPN on local

### ISSUE THREAD

**Issue by appsteady-dev** [alcalyn/payplug-bundle#17]
HI,
I m trying to handle IPNs, but I got an issue while using 
`php app/console payplug:simulate:ipn`

Got this error, no more informations...

```
[Symfony\Component\Debug\Exception\UndefinedMethodException]                                          
  Attempted to call an undefined method named "get" of class "TseBundle\EventListener\PaymentListener" 
```

Cache is clear ; working on debian 9 (Local code copy) ; PHP 7.0.19-1 ; Symfony 2.8 ;

regards

**Comment by alcalyn** [comment]
I didn't used this bundle for a while, but as the error is saying, it seems you're trying to do `$this->get()` in your listener, but your listener don't have any `get` method.

I guess you copy/pasted `$this->get` from documentation, but it was expected to be pasted in a controller, because controllers have a `get` method.

I could help you if you're say want you want to do, but you obviously need to inject the needed service  in your listener as your not in a controller which can access to any service from the container with `$this->get('service')`.

**Comment by appsteady-dev** [comment]
Hey,
I actually commented the part of your code I pasted  (involving the 'get' method)  , and just try to log something to check if I actually get the listener working... I'll search a bit deeper about any suspicious 'get' method ..


EDIT----
I m  affraid its my 	$logger = $this->get('logger');   that messes it up ...    not in a controller ^^

**Comment by appsteady-dev** [comment]
OK, it was my bad !!

thanks for answering
